# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\setup_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetupWindow(object):
    def setupUi(self, SetupWindow):
        SetupWindow.setObjectName("SetupWindow")
        SetupWindow.resize(391, 130)
        SetupWindow.setMinimumSize(QtCore.QSize(0, 0))
        SetupWindow.setMaximumSize(QtCore.QSize(400, 150))
        self.ent_account_sid = QtWidgets.QLineEdit(SetupWindow)
        self.ent_account_sid.setGeometry(QtCore.QRect(110, 24, 271, 20))
        self.ent_account_sid.setObjectName("ent_account_sid")
        self.ent_auth_token = QtWidgets.QLineEdit(SetupWindow)
        self.ent_auth_token.setGeometry(QtCore.QRect(110, 70, 271, 20))
        self.ent_auth_token.setObjectName("ent_auth_token")
        self.btn_account_sid = QtWidgets.QLabel(SetupWindow)
        self.btn_account_sid.setGeometry(QtCore.QRect(110, 9, 141, 16))
        self.btn_account_sid.setObjectName("btn_account_sid")
        self.lbl_auth_token = QtWidgets.QLabel(SetupWindow)
        self.lbl_auth_token.setGeometry(QtCore.QRect(110, 55, 141, 16))
        self.lbl_auth_token.setObjectName("lbl_auth_token")
        self.btn_submit = QtWidgets.QPushButton(SetupWindow)
        self.btn_submit.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.btn_cancel = QtWidgets.QPushButton(SetupWindow)
        self.btn_cancel.setGeometry(QtCore.QRect(210, 100, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label = QtWidgets.QLabel(SetupWindow)
        self.label.setGeometry(QtCore.QRect(14, 18, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\ui\\twilio_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(SetupWindow)
        QtCore.QMetaObject.connectSlotsByName(SetupWindow)

    def retranslateUi(self, SetupWindow):
        _translate = QtCore.QCoreApplication.translate
        SetupWindow.setWindowTitle(_translate("SetupWindow", "Form"))
        self.btn_account_sid.setText(_translate("SetupWindow", "Twilio Account SID"))
        self.lbl_auth_token.setText(_translate("SetupWindow", "Twilio Auth Token"))
        self.btn_submit.setText(_translate("SetupWindow", "Submit"))
        self.btn_cancel.setText(_translate("SetupWindow", "Cancel"))