# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\test_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test_mode(object):
    def setupUi(self, test_mode):
        test_mode.setObjectName("test_mode")
        test_mode.resize(758, 391)
        self.console = QtWidgets.QTextEdit(test_mode)
        self.console.setGeometry(QtCore.QRect(10, 20, 741, 361))
        self.console.setObjectName("console")
        self.label = QtWidgets.QLabel(test_mode)
        self.label.setGeometry(QtCore.QRect(11, 6, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(test_mode)
        QtCore.QMetaObject.connectSlotsByName(test_mode)

    def retranslateUi(self, test_mode):
        _translate = QtCore.QCoreApplication.translate
        test_mode.setWindowTitle(_translate("test_mode", "Form"))
        self.label.setText(_translate("test_mode", "Console"))
